# Generated by Django 3.2.15 on 2022-08-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_board_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='decription',
            new_name='description',
        ),
    ]
