# Generated by Django 3.2.15 on 2022-08-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
