# Generated by Django 3.2.15 on 2022-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_rename_decription_board_description'),
        ('cards', '0004_alter_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcard',
            name='boards',
            field=models.ManyToManyField(related_name='cards', related_query_name='card', to='boards.Board'),
        ),
    ]
